Integration specs
MustakimMasum/ror-blog-app pull request #8
Opened 2023-11-14 20:43 UTC by firepicaso

## Activities of this branch

- Fixed n+1 issues using console
- Installed capybara
- Installed database_cleaner
- Added spec files in spec/views folder
- Added tests for user index page
- Added tests for user show page
- Added tests for user post index page
- Added tests for user post show page

### Screenshots of the before and after n +1 problem solved
All posts by user page: before

![all_post_by_user_BEFORE](https://github.com/firepicaso/ror-blog-app/assets/19272609/8981d01c-1f30-443e-bb0a-5ac3f535f7ea)

All posts by user page: after

![all_post_by_user_AFTER4](https://github.com/firepicaso/ror-blog-app/assets/19272609/de7da20c-be99-483e-a0c5-174ab564efc1)

Specific post by user: before

![Specific_post_by_User_BEFORE](https://github.com/firepicaso/ror-blog-app/assets/19272609/7c48f76c-b7fc-443a-9968-e07679713807)

Specific post by user: after

![Specific_post_by_User_AFTER4](https://github.com/firepicaso/ror-blog-app/assets/19272609/e94a2687-e4ad-4917-832b-08fe24c086ff)

Kindly asking for a review

2023-11-14 22:10 UTC, Munsa1 requested changes
Hi @firepicaso, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Test Cases :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-14 22:10 UTC, Munsa1 commented on spec/views/users_show_spec.rb
> +  end
- [ ] For the User's show page, your tests should expect only 1 image of the current user to be present NOT 2 or more. This is because the User index page lists all the users, but when you click on each user you are then taken to the User show page which should show you the selected user's  profile with their 3 most recent posts. Kindly fix this test.

2023-11-14 22:10 UTC, Munsa1 commented on spec/views/users_show_spec.rb
> +
- [ ] Again here we should only be able to see one username as this is the User show page showing us an individual User. Kindly fix this
![image](https://github.com/firepicaso/ror-blog-app/assets/81932478/2a4e05b2-100d-4d4b-bdd2-008033d1e268)

2023-11-14 22:10 UTC, Munsa1 commented on spec/views/users_show_spec.rb
> +  end
- [ ] Same here we should only test for the selected user as this is the User show page.
![image](https://github.com/firepicaso/ror-blog-app/assets/81932478/02baae72-e01e-4702-8644-e35a398f7fba)

2023-11-14 22:10 UTC, Munsa1 commented on spec/views/users_show_spec.rb
> +  end
- [ ] The same applies for the bio as well, we should only test for the selected users bio and not for the second user as well. Kindly fix this

2023-11-14 22:10 UTC, Munsa1 commented on spec/views/posts_index_spec.rb
> +end
- [ ] As per requirement you need  to add a test which asserts that `you can see a section for pagination if there are more posts than fit on the view.`

2023-11-15 04:21 UTC, firepicaso commented on spec/views/users_show_spec.rb
> +  end
this is the user index page. and Im testing to see if the the individual photos are visible on the users index page.
@Munsa1

2023-11-15 05:17 UTC, firepicaso commented on spec/views/users_show_spec.rb
> +  end
appreciate the feedback @Munsa1

2023-11-15 05:27 UTC, MahmoudBakr23 approved these changes
Hi team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on addressing the requested changes from the previous reviewer

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 05:36 UTC, merged